# This file was generated by GoReleaser. DO NOT EDIT.
cask "arrbiter" do
  desc "Your media library's arbiter of taste - A CLI tool for managing Radarr movies with advanced filtering"
  homepage "https://github.com/s0up4200/arrbiter"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arrbiter"

  on_macos do
    on_intel do
      url "https://github.com/s0up4200/arrbiter/releases/download/v0.1.0/arrbiter_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "5f7cc3b7f574c4d66f4bdf1a59ed9901df23fef6d8dfc12efe7bd6f076106dbf"
    end
    on_arm do
      url "https://github.com/s0up4200/arrbiter/releases/download/v0.1.0/arrbiter_0.1.0_Darwin_arm64.tar.gz"
      sha256 "6744d41e5ed24404ada1fc9fc78ba33c8438c06a1df44a6f87146a5a8fe481ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s0up4200/arrbiter/releases/download/v0.1.0/arrbiter_0.1.0_Linux_x86_64.tar.gz"
      sha256 "abbf9917227ae96f1c32858b94281a96768460935cb334d278d677c765d2f48b"
    end
    on_arm do
      url "https://github.com/s0up4200/arrbiter/releases/download/v0.1.0/arrbiter_0.1.0_Linux_arm64.tar.gz"
      sha256 "a6adf8644ac31fc041dd320bc187117938ab3f88fe5e96a5e72ee1a02b17b46a"
    end
  end

  # No zap stanza required
end
