# This file was generated by GoReleaser. DO NOT EDIT.
cask "arrbiter" do
  desc "Your media library's arbiter of taste - A CLI tool for managing Radarr movies with advanced filtering"
  homepage "https://github.com/s0up4200/arrbiter"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "arrbiter"

  on_macos do
    on_intel do
      url "https://github.com/s0up4200/arrbiter/releases/download/v1.0.0/arrbiter_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "27035d70143c62503014b1ab6ca5aa990d9efcaf8d719570e9e4115fc8f2f92f"
    end
    on_arm do
      url "https://github.com/s0up4200/arrbiter/releases/download/v1.0.0/arrbiter_1.0.0_Darwin_arm64.tar.gz"
      sha256 "13b82c09db3fdf992a599f479ec860d73e71bf8c42334682158d872384edc81e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/s0up4200/arrbiter/releases/download/v1.0.0/arrbiter_1.0.0_Linux_x86_64.tar.gz"
      sha256 "82f1a9e363462e1a0220f068cbea49ccdc65fee7bd3c05e1b1151bd3847d5268"
    end
    on_arm do
      url "https://github.com/s0up4200/arrbiter/releases/download/v1.0.0/arrbiter_1.0.0_Linux_arm64.tar.gz"
      sha256 "9d81cac3a905cf7a458aef0f08db82907593c9fad7200dda90b4a1583db23e01"
    end
  end

  # No zap stanza required
end
